### ISSUE TITLE
panic: pg 18.48: conflicting mapping(s) found when trying to map from 72 to 527

### ISSUE THREAD

**Issue by timureh** [digitalocean/pgremapper#10]
Hi! 
What I've done:

drained osd
waited all active+clean
did norebalance, nobackfill flags
stopped this osd
did ceph osd purge for this osd
I got remapped pgs
When I tried to do a cancell-backfill I got a panic:
```
./pgremapper cancel-backfill --verbose
'--yes' is not provided, running in report mode

** executing: ceph osd dump -f json
** executing: ceph pg dump pgs_brief -f json
** executing: ceph osd dump -f json
** executing: ceph pg dump pgs_brief -f json
** executing: ceph osd dump -f json
** executing: ceph osd dump -f json
panic: pg 18.48: conflicting mapping(s) found when trying to map from 72 to 527

goroutine 82 [running]:
main.(*mappingState).remap(0xc0000123f0, 0xc000e5d605, 0x5, 0x48, 0x20f)
	/pgremapper/mappingstate.go:76 +0x7a5
main.calcPgMappingsToUndoBackfill.func3(0xc00094a000, 0xc000012300, 0xc0000126c0, 0xc000182cc0, 0xc000948000, 0xc000948010, 0xc001240040)
	/pgremapper/main.go:703 +0x3d3
created by main.calcPgMappingsToUndoBackfill
	/pgremapper/main.go:646 +0x1a5
```
All dumps are needed in the attachment 
[dump.zip](https://github.com/digitalocean/pgremapper/files/6940011/dump.zip)

**Comment by baergj** [comment]
Thanks for your report! I just got back from some time off and am looking at this now.

Here's the current upmap entry for the given PG:
```json
    {
      "pgid": "18.48",
      "mappings": [
        {
          "from": 72,
          "to": 606
        }
      ]
    },
```

And the current PG state:
```json
    {
      "pgid": "18.48",
      "state": "active+remapped+backfilling",
      "up": [
        72,
        165,
        606
      ],
      "acting": [
        165,
        606,
        527
      ],
      "up_primary": 72,
      "acting_primary": 165
    },
```

That existing mapping is stale (72->606 is obviously ignored given that both are in the up set). pgremapper will need to learn how to automatically clean up stale upmap items (something that Ceph should probably be doing itself, but alas).

To work around this, you can `ceph osd rm-pg-upmap-items 18.48` for now.

**Comment by timureh** [comment]
yes it solved the problem.
Thank you!

please clarify whether you plan to teach the pgremapper to detect such a situation and delete it automatically?

**Comment by baergj** [comment]
We definitely plan to fix this!

**Comment by k0ste** [comment]
Hope this fixable... Because sometimes this upmaps blocks pgremapper work not only 1-2 times 🥺
```python
   54  2021-09-01 11:35:07 ./upmap_cancel_backfill.sh
   55  2021-09-01 11:35:32 ceph osd rm-pg-upmap-items 47.fec
   56  2021-09-01 11:35:34 ./upmap_cancel_backfill.sh
   57  2021-09-01 11:35:41 ceph osd rm-pg-upmap-items 47.fbb
   58  2021-09-01 11:35:42 ./upmap_cancel_backfill.sh
   59  2021-09-01 11:35:49 ceph osd rm-pg-upmap-items 47.eed
   60  2021-09-01 11:35:50 ./upmap_cancel_backfill.sh
   61  2021-09-01 11:35:57 ceph osd rm-pg-upmap-items 47.eb1
   62  2021-09-01 11:35:58 ./upmap_cancel_backfill.sh
   63  2021-09-01 11:36:05 ceph osd rm-pg-upmap-items 47.599
   64  2021-09-01 11:36:08 ./upmap_cancel_backfill.sh
   65  2021-09-01 11:36:15 ceph osd rm-pg-upmap-items 47.367
   66  2021-09-01 11:36:17 ./upmap_cancel_backfill.sh
   67  2021-09-01 11:36:23 ceph osd rm-pg-upmap-items 47.e8
   68  2021-09-01 11:36:24 ./upmap_cancel_backfill.sh
   69  2021-09-01 11:36:30 ceph osd rm-pg-upmap-items 47.221
   70  2021-09-01 11:36:31 ./upmap_cancel_backfill.sh
   71  2021-09-01 11:36:37 ceph osd rm-pg-upmap-items 47.27a
   72  2021-09-01 11:36:39 ./upmap_cancel_backfill.sh
   73  2021-09-01 11:36:45 ceph osd rm-pg-upmap-items 47.6ce
   74  2021-09-01 11:36:46 ./upmap_cancel_backfill.sh
   75  2021-09-01 11:36:51 ceph osd rm-pg-upmap-items 47.9b6
   76  2021-09-01 11:36:53 ./upmap_cancel_backfill.sh
```
