### ISSUE TITLE
min_compat_client warning is not handled by pgremapper

### ISSUE THREAD

**Issue by k0ste** [digitalocean/pgremapper#11]
This panic:
```console
# ./upmap_cancel_backfill.sh --yes
** executing: ceph osd dump -f json
** executing: ceph pg dump pgs_brief -f json
** executing: ceph osd dump -f json
** executing: ceph pg dump pgs_brief -f json
** executing: ceph osd dump -f json
** executing: ceph osd dump -f json
** executing: ceph osd pg-upmap-items 3.0 39 7 6 37 66 48
** executing: ceph osd pg-upmap-items 3.1 6 88
** executing: ceph osd pg-upmap-items 3.101 89 90 123 124
** executing: ceph osd pg-upmap-items 3.10 130 84 93 134
** executing: ceph osd pg-upmap-items 3.100 35 19 4 49 143 84
panic: failed to execute command: ceph osd pg-upmap-items 3.1 6 88: exit status 1

goroutine 66 [running]:
main.runOrDie(0xc0001e2000, 0x6, 0x8, 0x4, 0x6)
        /pgremapper/main.go:993 +0x117
main.(*pgUpmapItem).do(0xc000458fa0)
        /pgremapper/ceph.go:259 +0x2c5
main.(*mappingState).apply.func1(0xc000547d40, 0xc000556b50)
        /pgremapper/mappingstate.go:200 +0x3f
created by main.(*mappingState).apply
        /pgremapper/mappingstate.go:198 +0xaa
```
Actual issue is:
```console
# ceph osd pg-upmap-items 3.1 6 88
Error EPERM: min_compat_client jewel < luminous, which is required for pg-upmap. Try 'ceph osd set-require-min-compat-client luminous' before using the new interface
````
It will be good if error stderr is handled and printed instead panic

**Comment by baergj** [comment]
Very good point! I'll put up a patch for this.
